# Generated by Django 4.1 on 2022-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bemor', models.CharField(max_length=50)),
                ('diagnoz', models.CharField(max_length=200)),
                ('firstrec', models.CharField(blank=True, max_length=100, null=True)),
                ('secondrec', models.CharField(blank=True, max_length=100, null=True)),
                ('thirdrec', models.CharField(blank=True, max_length=100, null=True)),
                ('fourthrec', models.CharField(blank=True, max_length=100, null=True)),
                ('fifthrec', models.CharField(blank=True, max_length=100, null=True)),
                ('sixthrec', models.CharField(blank=True, max_length=100, null=True)),
                ('seventhrec', models.CharField(blank=True, max_length=100, null=True)),
                ('eightthrec', models.CharField(blank=True, max_length=100, null=True)),
                ('ninethrec', models.CharField(blank=True, max_length=100, null=True)),
                ('tenthrec', models.CharField(blank=True, max_length=100, null=True)),
                ('eleventhrec', models.CharField(blank=True, max_length=100, null=True)),
                ('twelvethrec', models.CharField(blank=True, max_length=100, null=True)),
                ('thirdteenthrec', models.CharField(blank=True, max_length=100, null=True)),
                ('fourteenthrec', models.CharField(blank=True, max_length=100, null=True)),
                ('fifteenthrec', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
