# Generated by Django 4.1 on 2022-09-02 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bemor', models.CharField(max_length=45)),
                ('birthdate', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('kasalligi', models.TextField()),
                ('qayerga', models.CharField(max_length=100)),
                ('diagnoz', models.CharField(max_length=100)),
                ('whereas', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
