# Generated by Django 4.1 on 2022-09-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='carousel/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='carousel/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='carousel/')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('button', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
