# Generated by Django 4.1 on 2022-09-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='button',
            new_name='button1',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='header',
            new_name='header1',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='text',
            new_name='header2',
        ),
        migrations.AddField(
            model_name='carousel',
            name='button2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='button3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='header3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='text1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='text2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='text3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
